---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 180 seconds for target connection to become reachable/usable."
      command: sleep 180
    # - name: "install python"
    #   command: sudo apt-get install python

  roles:
    - configure-prometheus-node-exporter
    - configure-server
  
  environment:
    # We have to use the lookup functionality to get the environment variables we configured in
    # CircleCI.
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/env_lookup.html
    ENVIRONMENT: "production"
    TYPEORM_CONNECTION: "postgres"
    TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: 5532
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"