---
- name: "Copy Application Dependencies"
  become: true
  synchronize:
    src: ~/project/backend/node_modules
    dest: /home/ubuntu/udacity-p3
    recursive: true

- name: "Copy Built Application"
  become: true
  synchronize:
    src: ~/project/backend/dist
    dest: /home/ubuntu/udacity-p3
    recursive: true

- name: "Start Back-end Server with PM2"
  become: true
  command: pm2 start -f /home/ubuntu/udacity-p3/dist/main.js